[package]
name = "rhaki-cw-plus"
version = "0.1.0"
edition = "2021"
authors = ["Rhaki"]
description = "Advance utils for cosmwasm contract"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
