[package]
name                = "rhaki-cw-plus"
version             = "0.6.7"
edition             = "2021"
license             = "Apache-2.0"
authors             = ["Rhaki"]
description         = "Advanced utils for cosmwasm contract"
repository          = "https://github.com/Rhaki/rhaki-cw-plus"

[dependencies]
rhaki-cw-plus-macro = { path = "../macros", version = "0.1.0" }
cw-storage-plus     = { workspace = true, features = ["macro"] }
cosmwasm-std        = { workspace = true }
cosmwasm-schema     = { workspace = true }
cw-asset            = { workspace = true }
cw20                = { workspace = true }
serde-cw-value      = { workspace = true }
serde-json-wasm     = { workspace = true }
base64              = { workspace = true }
serde_json          = { workspace = true }
serde               = { workspace = true }
schemars            = { workspace = true }
forward_ref         = { workspace = true }
osmosis-std         = { workspace = true }
pyth-sdk-cw         = { workspace = true }
