[package]
name            = "rhaki-cw-plus"
version         = "0.2.0"
edition         = "2021"
license         = "Apache-2.0"
authors         = ["Rhaki"]
description     = "Advanced utils for cosmwasm contract"
repository      = "https://github.com/Rhaki/rhaki-cw-plus"

[dependencies]
cw-storage-plus = { version = "1.1.0" }
cosmwasm-std    = { version = "1.1.0" }
cosmwasm-schema = { version = "1.1.0" }
