[package]
name            = "rhaki-cw-plus"
version         = "0.2.3"
edition         = "2021"
license         = "Apache-2.0"
authors         = ["Rhaki"]
description     = "Advanced utils for cosmwasm contract"
repository      = "https://github.com/Rhaki/rhaki-cw-plus"

[dependencies]
cw-storage-plus = { version = "1.1.0"  }
cosmwasm-std    = { version = "1.1.0"  }
cosmwasm-schema = { version = "1.1.0"  }
serde-cw-value  = { version = "0.7.0"  }
serde-json-wasm = { version = "0.5.1"  } 
base64          = { version = "0.21.2" }
